import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'src/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Stream() {
  return (
    <>
      <Head>
        <title>Aplicación Ant Media Server</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Script type='module' src='/js/utility.js' />
        <video id="localVideo" autoPlay controls width={480} height={360}></video>
        <br/>
        <button id="publish_start">Start Publishing</button>
        <button id="publish_stop">Stop Publishing</button>
        <br/>
        <p id="status_info">Offline</p>
      </main>
    </>
  )
}
